(use 'lancet) 
(require 'lancet.ant)
(alias 'ant 'lancet.ant)

(def src "src")
(def jsrc (str src "/jvm"))
(def cljsrc (str src "/clj"))
(def build "classes")
(def clojure_jar "clojure.jar")
(def bootclj (str cljsrc "/clojure/boot.clj"))

(deftarget test-target
  "Simple echo to test plumbing"
  (ant/echo {:message "test target"}))
  
(deftarget init
  (ant/tstamp)
  (ant/mkdir {:dir build}))

(deftarget compile
  "Compile Java sources."
  (init)
  (ant/javac  {:srcdir jsrc :destdir build
	       :includejavaruntime "yes"
	       :debug "true"
	       :target "1.5"}))

(deftarget clean
  "Remove autogenerated files and directories"
  (ant/delete {:dir build}))

(deftarget jar
  "Create jar file."
  (compile)
  (ant/jar {:jarfile clojure_jar
	    :basedir build}))

;; TODO: tie together ant tasks and subsidiary data types
;;       such as fileset and manifest
	   
;;  (target {:name "jar" 
;;           :depends "compile"
;; 	  :description "Create jar file."}
;;   (jar {:jarfile clojure_jar
;;         :basedir build}
;;     (fileset {:dir cljsrc :includes "**/*.clj"})))
;; )
	 